# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{140proof-gltail}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["us"]
  s.date = %q{2010-03-29}
  s.default_executable = %q{gl_tail}
  s.description = %q{visualize 140 proof activity}
  s.email = %q{jm3@140proof.com}
  s.executables = ["gl_tail"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.txt"
  ]
  s.files = [
    ".gitignore",
     "140proof-gltail.gemspec",
     "LICENSE",
     "README.txt",
     "Rakefile",
     "VERSION",
     "bin/gl_tail",
     "config/140proof_api.yml",
     "config/140proof_db.yml",
     "config/goodness_generator.yml",
     "lib/gl_tail.rb",
     "lib/gl_tail/activity.rb",
     "lib/gl_tail/blob_store.rb",
     "lib/gl_tail/block.rb",
     "lib/gl_tail/config.rb",
     "lib/gl_tail/config/configurable.rb",
     "lib/gl_tail/config/yaml_parser.rb",
     "lib/gl_tail/element.rb",
     "lib/gl_tail/engine.rb",
     "lib/gl_tail/font.bin",
     "lib/gl_tail/font_store.rb",
     "lib/gl_tail/http_helper.rb",
     "lib/gl_tail/item.rb",
     "lib/gl_tail/parser.rb",
     "lib/gl_tail/parsers/apache.rb",
     "lib/gl_tail/parsers/asafwsm.rb",
     "lib/gl_tail/parsers/iis.rb",
     "lib/gl_tail/parsers/memcached.rb",
     "lib/gl_tail/parsers/mysql-slow.rb",
     "lib/gl_tail/parsers/mysql.rb",
     "lib/gl_tail/parsers/named.rb",
     "lib/gl_tail/parsers/nanite.rb",
     "lib/gl_tail/parsers/nginx.rb",
     "lib/gl_tail/parsers/onefortyproof.rb",
     "lib/gl_tail/parsers/pfsense.rb",
     "lib/gl_tail/parsers/pix-fwsm.rb",
     "lib/gl_tail/parsers/postfix.rb",
     "lib/gl_tail/parsers/postgresql.rb",
     "lib/gl_tail/parsers/pureftpd.rb",
     "lib/gl_tail/parsers/qmail.rb",
     "lib/gl_tail/parsers/rails.rb",
     "lib/gl_tail/parsers/sayplus1.rb",
     "lib/gl_tail/parsers/squid.rb",
     "lib/gl_tail/parsers/tshark.rb",
     "lib/gl_tail/resolver.rb",
     "lib/gl_tail/server.rb",
     "lib/gl_tail/sources/base.rb",
     "lib/gl_tail/sources/local.rb",
     "lib/gl_tail/sources/ssh.rb",
     "vendor/Chipmunk-4.1.0/CMakeLists.txt",
     "vendor/Chipmunk-4.1.0/Demo/CMakeLists.txt",
     "vendor/Chipmunk-4.1.0/Demo/Demo1.c",
     "vendor/Chipmunk-4.1.0/Demo/Demo2.c",
     "vendor/Chipmunk-4.1.0/Demo/Demo3.c",
     "vendor/Chipmunk-4.1.0/Demo/Demo4.c",
     "vendor/Chipmunk-4.1.0/Demo/Demo5.c",
     "vendor/Chipmunk-4.1.0/Demo/Demo6.c",
     "vendor/Chipmunk-4.1.0/Demo/Demo7.c",
     "vendor/Chipmunk-4.1.0/Demo/Demo8.c",
     "vendor/Chipmunk-4.1.0/Demo/build.sh",
     "vendor/Chipmunk-4.1.0/Demo/main.c",
     "vendor/Chipmunk-4.1.0/LICENSE.txt",
     "vendor/Chipmunk-4.1.0/MSVCSolution/Chipmunk4MSVC2k3.ncb",
     "vendor/Chipmunk-4.1.0/MSVCSolution/Chipmunk4MSVC2k3.sln",
     "vendor/Chipmunk-4.1.0/MSVCSolution/Chipmunk4MSVC2k3.suo",
     "vendor/Chipmunk-4.1.0/MSVCSolution/Chipmunk4MSVC2k3/ChipmunkMSVC.vcproj",
     "vendor/Chipmunk-4.1.0/MSVCSolution/glut.def",
     "vendor/Chipmunk-4.1.0/MSVCSolution/glut.h",
     "vendor/Chipmunk-4.1.0/MSVCSolution/glut32.dll",
     "vendor/Chipmunk-4.1.0/MSVCSolution/glut32.lib",
     "vendor/Chipmunk-4.1.0/README.txt",
     "vendor/Chipmunk-4.1.0/docsrc/chipmunk-docs.textile",
     "vendor/Chipmunk-4.1.0/docsrc/doc_dummy.rb",
     "vendor/Chipmunk-4.1.0/docsrc/makedocs.rb",
     "vendor/Chipmunk-4.1.0/macosx/Chipmunk.xcodeproj/project.pbxproj",
     "vendor/Chipmunk-4.1.0/macosx/main-Info.plist",
     "vendor/Chipmunk-4.1.0/ruby/CMakeLists.txt",
     "vendor/Chipmunk-4.1.0/ruby/chipmunk.c",
     "vendor/Chipmunk-4.1.0/ruby/chipmunk.h",
     "vendor/Chipmunk-4.1.0/ruby/cpArbiter.c",
     "vendor/Chipmunk-4.1.0/ruby/cpArbiter.h",
     "vendor/Chipmunk-4.1.0/ruby/cpArray.c",
     "vendor/Chipmunk-4.1.0/ruby/cpArray.h",
     "vendor/Chipmunk-4.1.0/ruby/cpBB.c",
     "vendor/Chipmunk-4.1.0/ruby/cpBB.h",
     "vendor/Chipmunk-4.1.0/ruby/cpBody.c",
     "vendor/Chipmunk-4.1.0/ruby/cpBody.h",
     "vendor/Chipmunk-4.1.0/ruby/cpCollision.c",
     "vendor/Chipmunk-4.1.0/ruby/cpCollision.h",
     "vendor/Chipmunk-4.1.0/ruby/cpHashSet.c",
     "vendor/Chipmunk-4.1.0/ruby/cpHashSet.h",
     "vendor/Chipmunk-4.1.0/ruby/cpJoint.c",
     "vendor/Chipmunk-4.1.0/ruby/cpJoint.h",
     "vendor/Chipmunk-4.1.0/ruby/cpPolyShape.c",
     "vendor/Chipmunk-4.1.0/ruby/cpPolyShape.h",
     "vendor/Chipmunk-4.1.0/ruby/cpShape.c",
     "vendor/Chipmunk-4.1.0/ruby/cpShape.h",
     "vendor/Chipmunk-4.1.0/ruby/cpSpace.c",
     "vendor/Chipmunk-4.1.0/ruby/cpSpace.h",
     "vendor/Chipmunk-4.1.0/ruby/cpSpaceHash.c",
     "vendor/Chipmunk-4.1.0/ruby/cpSpaceHash.h",
     "vendor/Chipmunk-4.1.0/ruby/cpVect.c",
     "vendor/Chipmunk-4.1.0/ruby/cpVect.h",
     "vendor/Chipmunk-4.1.0/ruby/extconf.rb",
     "vendor/Chipmunk-4.1.0/ruby/prime.h",
     "vendor/Chipmunk-4.1.0/ruby/rb_chipmunk.c",
     "vendor/Chipmunk-4.1.0/ruby/rb_chipmunk.h",
     "vendor/Chipmunk-4.1.0/ruby/rb_cpBB.c",
     "vendor/Chipmunk-4.1.0/ruby/rb_cpBody.c",
     "vendor/Chipmunk-4.1.0/ruby/rb_cpJoint.c",
     "vendor/Chipmunk-4.1.0/ruby/rb_cpShape.c",
     "vendor/Chipmunk-4.1.0/ruby/rb_cpSpace.c",
     "vendor/Chipmunk-4.1.0/ruby/rb_cpVect.c",
     "vendor/Chipmunk-4.1.0/src/CMakeLists.txt",
     "vendor/Chipmunk-4.1.0/src/chipmunk.c",
     "vendor/Chipmunk-4.1.0/src/chipmunk.h",
     "vendor/Chipmunk-4.1.0/src/cpArbiter.c",
     "vendor/Chipmunk-4.1.0/src/cpArbiter.h",
     "vendor/Chipmunk-4.1.0/src/cpArray.c",
     "vendor/Chipmunk-4.1.0/src/cpArray.h",
     "vendor/Chipmunk-4.1.0/src/cpBB.c",
     "vendor/Chipmunk-4.1.0/src/cpBB.h",
     "vendor/Chipmunk-4.1.0/src/cpBody.c",
     "vendor/Chipmunk-4.1.0/src/cpBody.h",
     "vendor/Chipmunk-4.1.0/src/cpCollision.c",
     "vendor/Chipmunk-4.1.0/src/cpCollision.h",
     "vendor/Chipmunk-4.1.0/src/cpHashSet.c",
     "vendor/Chipmunk-4.1.0/src/cpHashSet.h",
     "vendor/Chipmunk-4.1.0/src/cpJoint.c",
     "vendor/Chipmunk-4.1.0/src/cpJoint.h",
     "vendor/Chipmunk-4.1.0/src/cpPolyShape.c",
     "vendor/Chipmunk-4.1.0/src/cpPolyShape.h",
     "vendor/Chipmunk-4.1.0/src/cpShape.c",
     "vendor/Chipmunk-4.1.0/src/cpShape.h",
     "vendor/Chipmunk-4.1.0/src/cpSpace.c",
     "vendor/Chipmunk-4.1.0/src/cpSpace.h",
     "vendor/Chipmunk-4.1.0/src/cpSpaceHash.c",
     "vendor/Chipmunk-4.1.0/src/cpSpaceHash.h",
     "vendor/Chipmunk-4.1.0/src/cpVect.c",
     "vendor/Chipmunk-4.1.0/src/cpVect.h",
     "vendor/Chipmunk-4.1.0/src/prime.h"
  ]
  s.homepage = %q{http://140proof.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{visualize 140 proof activity}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<net-ssh>, ["~> 2.0"])
      s.add_runtime_dependency(%q<ruby-opengl>, ["~> 0.60"])
    else
      s.add_dependency(%q<net-ssh>, ["~> 2.0"])
      s.add_dependency(%q<ruby-opengl>, ["~> 0.60"])
    end
  else
    s.add_dependency(%q<net-ssh>, ["~> 2.0"])
    s.add_dependency(%q<ruby-opengl>, ["~> 0.60"])
  end
end

